#声明自己是个client 并且注册server的地址
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/ #http://eureka.didispace.com/eureka/

#微服务通过name作为标识
#配置zipkin服务地址
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: helloworld
  sleuth:
    sampler:
      probability: 1.0
    enabled: true


server:
  port: 8762




