#声明自己是个client 并且注册server的地址
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/ #http://eureka.didispace.com/eureka/

#微服务通过name作为标识
spring:
  application:
    name: helloworld

server:
  port: 8762


