eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #http://eureka.didispace.com/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
    enabled: true


#feign默认集成hystrix 此为开启配置
feign:
  hystrix:
    enabled: true
